name: Flutter

on:
  push:
  pull_request:

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Build Web App
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
